name : Test github action
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hello World
        run: echo 'Hello world action'
    
      
    
  

